<a href="https://colab.research.google.com/github/abdinegara783/FindIT2023/blob/Experiment/FindIT_Random_Forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [98]:
import pandas as pd

from google.colab import drive
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, GridSearchCV

In [99]:
# Mount Google Drive to access dataset
drive.mount('/content/drive', force_remount=True)

# Set up directory path
file_path = '/content/drive/MyDrive/df_TrainingFeatures.csv'
target_path = '/content/drive/MyDrive/training_set_labels.csv'

Mounted at /content/drive

In [100]:
# Read CSV file
data = pd.read_csv(file_path)

# Print the contents of the CSV file
data.head()

,respondent_id,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,race_White,"income_poverty_<= $75,000, Above Poverty","income_poverty_> $75,000",income_poverty_Below Poverty,employment_status_Employed,employment_status_Not in Labor Force,employment_status_Unemployed,"census_msa_MSA, Not Principle City","census_msa_MSA, Principle City",census_msa_Non-MSA
0,0,1,0,0,0,0,0,0,1,1,...,1,0,0,1,0,1,0,0,0,1
1,1,3,2,0,1,0,1,0,1,1,...,1,0,0,1,1,0,0,1,0,0
2,2,1,1,0,1,0,0,0,0,0,...,1,1,0,0,1,0,0,1,0,0
3,3,1,1,0,1,0,1,1,0,0,...,1,0,0,1,0,1,0,0,1,0
4,4,2,1,0,1,0,1,1,0,1,...,1,1,0,0,1,0,0,1,0,0

In [101]:
# Read CSV file
target = pd.read_csv(target_path)

# Print the contents of the CSV file
target.head()

   respondent_id  h1n1_vaccine  seasonal_vaccine
0              0             0                 0
1              1             0                 1
2              2             0                 0
3              3             0                 1
4              4             0                 0

In [102]:
# merge the dataframes using respondent_id as primary key
merged_df = pd.merge(data, target, on='respondent_id')

# print the merged dataframe
merged_df.head()

,respondent_id,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,"income_poverty_> $75,000",income_poverty_Below Poverty,employment_status_Employed,employment_status_Not in Labor Force,employment_status_Unemployed,"census_msa_MSA, Not Principle City","census_msa_MSA, Principle City",census_msa_Non-MSA,h1n1_vaccine,seasonal_vaccine
0,0,1,0,0,0,0,0,0,1,1,...,0,1,0,1,0,0,0,1,0,0
1,1,3,2,0,1,0,1,0,1,1,...,0,1,1,0,0,1,0,0,0,1
2,2,1,1,0,1,0,0,0,0,0,...,0,0,1,0,0,1,0,0,0,0
3,3,1,1,0,1,0,1,1,0,0,...,0,1,0,1,0,0,1,0,0,1
4,4,2,1,0,1,0,1,1,0,1,...,0,0,1,0,0,1,0,0,0,0

In [103]:
merged_df.to_csv('data_and_target.csv', index=False)

In [104]:
# copy dataframe df menjadi df1 dan df2
df1 = merged_df.copy()
df2 = merged_df.copy()

# **Code for Target 1**

In [105]:
# memisahkan feature dan label
X = df1.iloc[:, :-1].values
y = df1.iloc[:, -1].values

# membagi dataset menjadi train set dan test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# membuat objek model
model = RandomForestClassifier()

In [106]:
# membuat dictionary parameter yang akan dicari
param_grid = {
    'n_estimators': [50, 100, 200, 300],
    'max_depth': [None, 5, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

In [ ]:
# melakukan grid search dengan cross-validation
grid_search = GridSearchCV(model, param_grid, cv=5)
grid_search.fit(X_train, y_train)

# menampilkan parameter terbaik dan skor validasi terbaik
print(f'Best Parameter: {grid_search.best_params_}')
print(f'Best CV Score  : {grid_search.best_score_}')

In [ ]:
# membuat objek model baru dengan parameter terbaik
best_model = RandomForestClassifier(**grid_search.best_params_)

# melatih ulang model pada data latih
best_model.fit(X_train, y_train)

# melakukan prediksi pada data uji
y_pred = best_model.predict(X_test)

# menghitung akurasi model pada data uji
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

# **Code for Target 2**

In [ ]:
# memisahkan feature dan label
X = df2.iloc[:, :-1].values
y = df2.iloc[:, -1].values

# membagi dataset menjadi train set dan test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# membuat objek model
model = RandomForestClassifier()

In [ ]:
# membuat dictionary parameter yang akan dicari
param_grid = {
    'n_estimators': [50, 100, 200, 300],
    'max_depth': [None, 5, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

In [ ]:
# melakukan grid search dengan cross-validation
grid_search = GridSearchCV(model, param_grid, cv=5)
grid_search.fit(X_train, y_train)

# menampilkan parameter terbaik dan skor validasi terbaik
print(f'Best Parameter: {grid_search.best_params_}')
print(f'Best CV Score  : {grid_search.best_score_}')

In [ ]:
# membuat objek model baru dengan parameter terbaik
best_model = RandomForestClassifier(**grid_search.best_params_)

# melatih ulang model pada data latih
best_model.fit(X_train, y_train)

# melakukan prediksi pada data uji
y_pred = best_model.predict(X_test)

# menghitung akurasi model pada data uji
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')